### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-backend#11]
Add the following Jenkins jobs (set all to build on the ci-prototype-jenkins slave):
* build-center-new-backend
* deploy-new-backend

On the jenkins slave, we'll need:
* python 3.4.3
* virtualenv
* dependencies in `requirements.txt`
* node/npm
* bower/gulp/grunt?

**Comment by blaino** [comment]
Have to install ozp-common from new-backend branch, yes?

**Comment by arw180** [comment]
Correct - this is done in the Jenkins Job itself (we just `sed` the `package.json` file)

**Comment by arw180** [comment]
Closing since this is all being tracked by #12 now
