### ISSUE TITLE
Quickview Modal - Sometimes owners are not displayed on Details tab

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-backend#119]
@clarkjefcoat commented on [Thu Mar 17 2016](https://github.com/ozone-development/ozp-center/issues/548)

When a listing has multiple owners the "Owner(s):" portion of the Details tab is blank.

**Comment by clarkjefcoat** [comment]
The original title for this ticket was confusing.  The issue is not with multiple owners, the issue is that the /storefront call was not returning enough information about the owners to have them displayed correctly.

**Comment by tdressel** [comment]
Passed on Latest.
