### ISSUE TITLE
feat(Listing): Add bookmarked attribute to listing object

### ISSUE THREAD

**Issue by rkenyon1969** [ozone-development/ozp-backend#159]
Add additional attribute to Listing when serializing in ozp-backend. The attribute will be used in ozp-center to determine if bookmark exists whether or not Listing is enabled.

**Comment by rkenyon1969** [comment]
Issue moved to [ozone-development/ozp-center #612](https://github.com/ozone-development/ozp-center/issues/612) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by tdressel** [comment]
Passed.
