### ISSUE TITLE
Unable to run ozp-backend on Windows 8.1

### ISSUE THREAD

**Issue by chazzlabs** [ozone-development/ozp-backend#200]
Following the instructions in the README, I'm unable to run ozp-backend on Windows 8.1.  I'm getting this error in the Traceback:
> redis.exceptions.ConnectionError: Error 10061 connecting to None:6379. No connection could be made because the target machine actively refused it.

I've tried the following without success:

- Ignoring memcached exceptions using both suggestions here: http://niwinz.github.io/django-redis/latest/#_memcached_exceptions_behavior

- Prefixing the default caches location with ```redis://``` per the suggestion here: http://stackoverflow.com/a/27382430/1911273

- Uncommenting the line ```# "REDIS_CLIENT_CLASS": "mockredis.mock_strict_redis_client"``` in the default caches options per the instruction to comment it for production.

It's worth noting, I think, that the README has this instruction: 
>Run the server: ./restart_clean_dev_server.sh

However, since this file no longer exists and was replaced with a makefile, I installed Make for Windows and ran ```make dev``` instead, as it seemed to be the replacement for the shell script.

For completeness, here's the entirety of the output of my ```make dev``` run.  I think it's also worth noting that I get the same output when running this on both master and the 1.0.22 release.

>λ make dev
rm -f db.sqlite3
rm -rf static/
rm -rf media/
rm -f ozp.log
export DJANGO_SETTINGS_MODULE=ozp.settings
mkdir -p static
python manage.py collectstatic --noinput
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\css\base.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\css\changelists.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\css\dashboard.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\css\forms.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\css\ie.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\css\login.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\css\rtl.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\css\widgets.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\changelist-bg.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\changelist-bg_rtl.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\default-bg-reverse.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\default-bg.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\deleted-overlay.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon-no.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon-unknown.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon-yes.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_addlink.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_alert.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_calendar.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_changelink.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_clock.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_deletelink.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_error.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_searchbox.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\icon_success.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\inline-delete-8bit.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\inline-delete.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\inline-restore-8bit.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\inline-restore.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\inline-splitter-bg.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\nav-bg-grabber.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\nav-bg-reverse.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\nav-bg-selected.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\nav-bg.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\selector-icons.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\selector-search.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\sorting-icons.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\tooltag-add.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\tooltag-arrowright.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\gis\move_vertex_off.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\img\gis\move_vertex_on.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\actions.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\actions.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\calendar.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\collapse.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\collapse.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\core.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\inlines.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\inlines.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\jquery.init.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\jquery.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\jquery.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\LICENSE-JQUERY.txt'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\prepopulate.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\prepopulate.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\related-widget-wrapper.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\SelectBox.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\SelectFilter2.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\timeparse.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\urlify.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\admin\DateTimeShortcuts.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\contrib\admin\static\admin\js\admin\RelatedObjectLookups.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\css\bootstrap-tweaks.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\css\bootstrap.min.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\css\default.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\css\prettify.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\fonts\glyphicons-halflings-regular.eot'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\fonts\glyphicons-halflings-regular.svg'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\fonts\glyphicons-halflings-regular.ttf'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\fonts\glyphicons-halflings-regular.woff'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\img\glyphicons-halflings-white.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\img\glyphicons-halflings.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\img\grid.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\js\bootstrap.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\js\default.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\js\jquery-1.8.1-min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework\static\rest_framework\js\prettify-min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\static\django_extensions\css\jquery.autocomplete.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\static\django_extensions\img\indicator.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\static\django_extensions\js\jquery-1.7.2.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\static\django_extensions\js\jquery.ajaxQueue.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\static\django_extensions\js\jquery.autocomplete.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\static\django_extensions\js\jquery.bgiframe.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\index.html'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\o2c.html'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\swagger-ui.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\swagger-ui.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\css\atelier-dune.light.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\css\highlight.default.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\css\rest_framework_swagger.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\css\screen.css'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\images\explorer_icons.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\images\logo_small.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\images\pet_store_api.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\images\throbber.gif'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\images\wordnik_api.png'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\backbone-min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\handlebars-1.0.0.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\highlight.7.3.pack.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\highlight.8.0.pack.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\jquery-1.8.0.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\jquery.ba-bbq.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\jquery.cookie.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\jquery.slideto.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\jquery.wiggle.min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\shred.bundle.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\swagger-oauth.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\swagger.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\underscore-min.js'
Copying 'C:\Users\<user>\Envs\ozp-backend\lib\site-packages\rest_framework_swagger\static\rest_framework_swagger\lib\shred\content.js'

>110 static files copied to 'C:\dev\ozone\ozp-backend\static'.
mkdir -p media
python manage.py makemigrations ozpcenter
No changes detected in app 'ozpcenter'
python manage.py makemigrations ozpiwc
No changes detected in app 'ozpiwc'
python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: corsheaders, messages, rest_framework_swagger, rest_framework, staticfiles, django_extensions
  Apply all migrations: ozpiwc, admin, auth, ozpcenter, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table corsheaders_corsmodel
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying ozpcenter.0001_initial... OK
  Applying ozpcenter.0002_auto_20160310_1929... OK
  Applying ozpcenter.0003_listing_is_deleted... OK
  Applying ozpcenter.0004_auto_20160511_1653... OK
  Applying ozpcenter.0005_notification_agency... OK
  Applying ozpcenter.0006_notification__peer... OK
  Applying ozpiwc.0001_initial... OK
  Applying sessions.0001_initial... OK
echo 'Loading sample data...'
Loading sample data...
python manage.py runscript sample_data_generator
Exception while running run() in 'ozpcenter.scripts.sample_data_generator'
Traceback (most recent call last):
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_redis\cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_redis\cache.py", line 95, in delete_pattern
    return self.client.delete_pattern(*args, **kwargs)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_redis\client\default.py", line 269, in delete_pattern
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to None:6379. No connection could be made because the target machine actively refused it.

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\core\management\__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\management\email_notifications.py", line 63, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\core\management\base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\management\email_notifications.py", line 75, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\core\management\base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\management\utils.py", line 71, in inner
    ret = func(self, *args, **kwargs)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\management\commands\runscript.py", line 172, in handle
    run_script(mod, *script_args)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_extensions\management\commands\runscript.py", line 80, in run_script
    mod.run(*script_args)
  File "C:\dev\ozone\ozp-backend\ozpcenter\scripts\sample_data_generator.py", line 59, in run
    books_ref.save()
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\db\models\base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\db\models\base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django\dispatch\dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\dev\ozone\ozp-backend\ozpcenter\models.py", line 322, in post_save_category
    cache.delete_pattern('metadata-*')
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_redis\cache.py", line 39, in _decorator
    raise e.parent
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\django_redis\client\default.py", line 264, in delete_pattern
    for key in client.scan_iter(pattern):
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\redis\client.py", line 1383, in scan_iter
    cursor, data = self.scan(cursor=cursor, match=match, count=count)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\redis\client.py", line 1370, in scan
    return self.execute_command('SCAN', *pieces)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\redis\client.py", line 578, in execute_command
    connection.send_command(*args)
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\redis\connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\redis\connection.py", line 538, in send_packed_command
    self.connect()
  File "C:\Users\<user>\Envs\ozp-backend\lib\site-packages\redis\connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to None:6379. No connection could be made because the target machine actively refused it.
make: *** [dev] Error 1

**Comment by mannyrivera2010** [comment]
````python
redis.exceptions.ConnectionError: Error 10061 connecting to None:6379. No connection could be made because the target machine actively refused it.
````
"None:6379" is connecting to nothing.  

See if this works if you change the settings.py file
````python
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'localhost:6379',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "REDIS_CLIENT_CLASS": "mockredis.mock_strict_redis_client"
        }
    },
}
````
and run ````make dev```` again

**Comment by chazzlabs** [comment]
@mannyrivera2010 Per your suggestion I've commented the lines
```
"COMPRESSOR": "django_redis.compressors.lzma.LzmaCompressor",
"SERIALIZER": "django_redis.serializers.msgpack.MSGPackSerializer",
```
and uncommented the line
```
"REDIS_CLIENT_CLASS": "mockredis.mock_strict_redis_client",
```

This is similar to the solution I attempted in my third bullet.  After making the change you suggested, ```make dev``` hangs at ```python manage.py runscript sample_data_generator```

**Comment by mannyrivera2010** [comment]
````python manage.py runscript sample_data_generator```` will take 3-5 minutes to run complete.  you can verify that is is running if you see db.sqlite3-journal file in the ozp-backend directory

**Comment by chazzlabs** [comment]
This resolved my issue.  Turns out I just wasn't being patient enough.  Thanks, @mannyrivera2010.
