### ISSUE TITLE
Add endpoints for the Quickview->Administration tab

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-backend#23]
Adding support for the Administration tab requires understanding how the activity logs should work. At a minimum, we'll need the following:

* `GET listing/<id>/activity` - return all activity for this listing, including:
  * activity_date
  * change_details
  * author
  * listing
  * action
  * id
* `PUT listing/<id>` - update a listing (for toggling featured and enabled). data: everything you can imagine

**Comment by arw180** [comment]
Backend complete

**Comment by tdressel** [comment]
Passed https://ci-latest.amlng.di2e.net/admin/ozpcenter/listingactivity/455/
