### ISSUE TITLE
Center->Settings->Categories endpoints

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-backend#24]
Backend endpoints to support Center categories CRUD page

Current endpoints:
* `GET api/category?cmd=get-records&limit=100&offset=0`
* `POST api/category`. data = `{“title”: “cat title”, “description”: “cat desc”}`
* `PUT api/category/<id>`. data = (same as POST)
* `DELETE api/category/<id>`

**Comment by arw180** [comment]
Backend complete

**Comment by tdressel** [comment]
Tested using Postman 
GET https://ci-latest.amlng.di2e.net/center/#/api/category?cmd=get-records&limit=100&offset=0
RESULTS - 200 OK

**Comment by tdressel** [comment]
Tested all functions against latest.
