### ISSUE TITLE
Center->Listing Management->All Center Listings endpoints

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-backend#30]
* `GET api/listing` - must support offset, limit (max)
* `GET listing?approvalStatus=APPROVED&offset=0&max=24`
* `GET listing?approvalStatus=PENDING&offset=0&max=24` (Pending, Org)
* `GET listing?approvalStatus=REJECTED&offset=0&max=24` (Returned)
* `GET listing?approvalStatus=IN_PROGRESS&offset=0&max=24` (Draft)

* `GET listing?approvalStatus=IN_PROGRESS&org=Test+2+Organization&offset=0&max=24`
* `GET listing?approvalStatus=IN_PROGRESS&org=Test+2+Organization&enabled=true&offset=0&max=24`

Needs Action: approvedStatus=APPROVED_ORG

Query params (single values, not lists): offset, limit, approvalStatus, org, enabled

**Comment by arw180** [comment]
changing `max` to `limit`

**Comment by arw180** [comment]
Backend complete

**Comment by tdressel** [comment]
Passed
