### ISSUE TITLE
Create new image endpoint

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-backend#54]
`POST api/image`

**Comment by arw180** [comment]
To POST an image:
* use endpoint `POST api/image/`
* content_type = `application/form-data`
* data key/values: `access_control = UNCLASSIFIED, image_type = listing_small_screenshot, file_extension = png, image = <file>`

**Comment by tdressel** [comment]
Passed using https://ci-latest.amlng.di2e.net/admin/ozpcenter/image/
