### ISSUE TITLE
Most Popular Apps are not really sorted by popularity

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-backend#91]
What makes an app "Most Popular"?
STR-
Go to Homepage
DIO (1 review) and Bedrock (9 reviews) both with all 5 Star Ratings
RESULTS- DIO is sorted and listed before Bedrock.
EXPECTED RESULTS - Bedrock should display before DIO because it is "more popular"

**Comment by clarkjefcoat** [comment]
Closing as a dup of #73
