### ISSUE TITLE
Submit a Listing hangs on Uploading images when saved.

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-backend#93]
Add a Listing
After adding all images 
Submit Listing.
RESULTS - Hangs on Uploading images
EXPECTED RESULTS - Should not hang.

Bug originally reported as an ozp-center bug at https://github.com/ozone-development/ozp-center/issues/523

**Comment by mannyrivera2010** [comment]
This bug was confirmed.  This issue was a front-end error. The front-end passed in the wrong file extension to the backend.  
````
{
            'security_marking': 'UNCLASSIFIED',
            'image_type': 'small_screenshot',
            'file_extension': 'png',   <<<  This value should be based on the file name extension of the image key value
            'image': 'test.jpg')
}
````
TO

{
            'security_marking': 'UNCLASSIFIED',
            'image_type': 'small_screenshot',
            'file_extension': '{jpg, png,gif}',  
            'image': 'test.{jpg,png,gif}'   where both {} are the same  
}
````
