### ISSUE TITLE
Saving Contacts is broken

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-backend#95]
In the data inherited from the old system we have multiple entries in the Contacts table that are exactly alike.  If we add a contact to a new listing with the same type, name, email, telephone, etc. as an existing contact with multiple entries then the listing will not save.

**Comment by clarkjefcoat** [comment]
The problem is that the method call models.Contact.objects.get_or_create() in ozpcenter/api/listing/serializers.py fails if it finds multiple matches.

**Comment by clarkjefcoat** [comment]
We should fix this in the data migration script so that we do not encounter this situation in the database.

**Comment by clarkjefcoat** [comment]
This required a code change in addition to a migration change.

**Comment by tdressel** [comment]
Able to add the same contact type to two separate listings without conflict.

**Comment by tdressel** [comment]
Passed on Staging.
